name: Chris Childs
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

theme: jekyll-theme-merlot
collections:
  blog posts:
     output: true
  fiction:
    output: true
  non-fiction:
    output: true
  art:
    output: true
  music:
    output: true
